name: flutter_cache_store_example
author: eGust<egustc@gmail.com>
homepage: https://github.com/eGust/flutter_cache_store

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_store:
    path: ../
