name: flutter_cache_store
description: More configurable cache manager for Flutter. Cache http get requests to mobile devices file system.
version: 0.7.1
author: eGust<egustc@gmail.com>
homepage: https://github.com/eGust/flutter_cache_store

environment:
  sdk: ">=2.1.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "^0.5.0"
  path_provider: "^1.1.0"
  synchronized: "^2.1.0"
  http: "^0.12.0"
